# Generated by Django 3.0.1 on 2019-12-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abksoftech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_img',
            field=models.ImageField(default='', upload_to='abksoftech/images'),
        ),
    ]
